[package.build.backend]
channels = ["https://prefix.dev/conda-forge"]
name = "pixi-build-ros"
version = "*"

[package.build.config]
distro = "jazzy"
extra-input-globs = [
  "CMakeLists.txt",
  "src/**/*.cpp",
  "config/*.yaml",
]
